# Generated by Django 5.2.6 on 2025-10-29 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='incidence_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date_time', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('not sellable with stock', 'not sellable with stock'), ('incorrect prices / no stock', 'incorrect prices / no stock')], max_length=50)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('marketplace_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.marketplace')),
            ],
        ),
    ]
