# Generated by Django 5.2.6 on 2025-10-29 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0001_initial'),
        ('products', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_incidence_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField()),
                ('incidence_report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidences.incidence_report')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
