# Generated by Django 5.2.6 on 2025-10-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0002_product_incidence_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='no_stock_incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('incidence_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidences.product_incidence_group')),
            ],
        ),
    ]
