# Generated by Django 5.2.6 on 2025-10-29 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0005_special_price_incidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='unsellable_incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('incidence_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidences.product_incidence_group')),
            ],
        ),
    ]
