# Generated by Django 5.2.6 on 2025-10-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0006_unsellable_incidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_incidence_group',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
