# Generated by Django 5.2.6 on 2025-10-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0007_alter_product_incidence_group_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence_report',
            name='inspected_products',
            field=models.PositiveIntegerField(default=54),
            preserve_default=False,
        ),
    ]
