# Generated by Django 5.2.6 on 2025-10-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0008_incidence_report_inspected_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence_report',
            name='report_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
