# Generated by Django 5.2.6 on 2025-11-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0009_incidence_report_report_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence_report',
            name='incidences_found',
            field=models.BooleanField(default=False),
        ),
    ]
