# Generated by Django 5.2.6 on 2025-11-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0010_incidence_report_incidences_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidence_report',
            name='incidences_found',
        ),
    ]
