# Generated by Django 5.2.6 on 2025-12-02 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0011_remove_incidence_report_incidences_found'),
        ('products', '0005_marketplace_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='not_accessible_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_status_code', models.PositiveIntegerField()),
                ('incidence_report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidences.incidence_report')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
