# Generated by Django 5.2.6 on 2025-12-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0012_not_accessible_product'),
        ('products', '0005_marketplace_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='not_accessible_product',
            new_name='not_scrapeable_product',
        ),
    ]
