# Generated by Django 5.2.6 on 2025-12-18 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0013_rename_not_accessible_product_not_scrapeable_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='existing_product_not_local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30)),
                ('sku_marketplace', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=100)),
                ('product_url', models.URLField(blank=True, null=True)),
                ('incidence_report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidences.incidence_report')),
            ],
        ),
    ]
