# Generated by Django 5.2.6 on 2026-01-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0014_existing_product_not_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence_report',
            name='report_status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], default='ggg', max_length=15),
            preserve_default=False,
        ),
    ]
