# Generated by Django 5.2.6 on 2026-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0015_incidence_report_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence_report',
            name='inspected_products',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
