# Generated by Django 5.2.6 on 2026-01-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0016_alter_incidence_report_inspected_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence_report',
            name='error_message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='incidence_report',
            name='report_status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=15),
        ),
    ]
