# Generated by Django 5.2.6 on 2026-01-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0017_incidence_report_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence_report',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
