# Generated by Django 5.2.6 on 2025-10-23 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('normal_price', models.PositiveIntegerField()),
                ('special_price', models.PositiveIntegerField(blank=True, null=True)),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('marketplace_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.marketplace')),
            ],
        ),
    ]
