# Generated by Django 5.2.6 on 2025-11-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku_marketplace',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
