# Generated by Django 5.2.6 on 2025-11-12 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sku_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='normal_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
