# Generated by Django 5.2.6 on 2025-11-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_normal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
